using System.ComponentModel.DataAnnotations;

namespace Backend.Models;

//person sınıfı
public class Person
{
    public int Id { get; set; }//primary key values will be generated by the db
    //Bir int değişkeni tanımlandığında, eğer başlangıç değeri verilmezse: 0 olarak başlar.


    [Required]
    [MaxLength(30)]
    public string FirstName { get; set; } = string.Empty; //= null, eğer değere verilmezse boş string olarak başlayark

    [Required]
    [MaxLength(30)]
    public string LastName { get; set; } = string.Empty; //= null, eğer değere verilmezse boş string olarak başlayark

}